/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/cisco-virl.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ciscovirl.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module cisco-virl.yang */
public class ciscovirl extends ConfNamespace {
    public static final int hash = 1894055485;
    public int hash() {
        return ciscovirl.hash;
    }

    public static final String id = "http://com/example/ciscovirl";
    public String id() {
        return ciscovirl.id;
    }

    public static final String uri = "http://com/example/ciscovirl";
    public String uri() {
        return ciscovirl.uri;
    }

    public static final String prefix = "cisco-virl";
    public String prefix() {
        return ciscovirl.prefix;
    }

    public ciscovirl() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _commands = 913421552;
    public static final String _commands_ = "commands";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _annotation_xmlnsXSI = 46830028;
    public static final String _annotation_xmlnsXSI_ = "annotation-xmlnsXSI";
    public static final int    _annotation_xmlns = 1742709667;
    public static final String _annotation_xmlns_ = "annotation-xmlns";
    public static final int    _location = 1827424758;
    public static final String _location_ = "location";
    public static final int    _Start_Simulation = 966888399;
    public static final String _Start_Simulation_ = "Start-Simulation";
    public static final int    _annotation_schemaVersion = 1213441422;
    public static final String _annotation_schemaVersion_ = "annotation-schemaVersion";
    public static final int    _topology_xml = 1084091422;
    public static final String _topology_xml_ = "topology-xml";
    public static final int    _subtype = 1955371587;
    public static final String _subtype_ = "subtype";
    public static final int    _excludeFromLaunch = 2125079005;
    public static final String _excludeFromLaunch_ = "excludeFromLaunch";
    public static final int    _extensions = 6037758;
    public static final String _extensions_ = "extensions";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _netPrefixLenV4 = 204259445;
    public static final String _netPrefixLenV4_ = "netPrefixLenV4";
    public static final int    _connection_index = 830553501;
    public static final String _connection_index_ = "connection-index";
    public static final int    _simulation_name = 1888339343;
    public static final String _simulation_name_ = "simulation-name";
    public static final int    _cisco_virl_id = 819869288;
    public static final String _cisco_virl_id_ = "cisco-virl-id";
    public static final int    _topology_name = 595636554;
    public static final String _topology_name_ = "topology-name";
    public static final int    _src = 1474138878;
    public static final String _src_ = "src";
    public static final int    _connection = 1134114300;
    public static final String _connection_ = "connection";
    public static final int    _simulation = 269615489;
    public static final String _simulation_ = "simulation";
    public static final int    _dst = 1772754210;
    public static final String _dst_ = "dst";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _entry = 1974505388;
    public static final String _entry_ = "entry";
    public static final int    _key = 1348858669;
    public static final String _key_ = "key";
    public static final int    _Stop_Simulation = 646475770;
    public static final String _Stop_Simulation_ = "Stop-Simulation";
    public static final int    _annotation_xsiSchemaLocation = 894690033;
    public static final String _annotation_xsiSchemaLocation_ = "annotation-xsiSchemaLocation";
}
