/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/cisco-virl.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ciscovirl.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module cisco-virl.yang */
public class ciscovirl extends ConfNamespace {
    public static final int hash = 1894055485;
    public int hash() {
        return ciscovirl.hash;
    }

    public static final String id = "http://com/example/ciscovirl";
    public String id() {
        return ciscovirl.id;
    }

    public static final String uri = "http://com/example/ciscovirl";
    public String uri() {
        return ciscovirl.uri;
    }

    public static final String prefix = "cisco-virl";
    public String prefix() {
        return ciscovirl.prefix;
    }

    public ciscovirl() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _commands = 913421552;
    public static final String _commands_ = "commands";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _Start_Simulation = 966888399;
    public static final String _Start_Simulation_ = "Start-Simulation";
    public static final int    _topology_xml = 1084091422;
    public static final String _topology_xml_ = "topology-xml";
    public static final int    _simulation_name = 1888339343;
    public static final String _simulation_name_ = "simulation-name";
    public static final int    _cisco_virl_id = 819869288;
    public static final String _cisco_virl_id_ = "cisco-virl-id";
    public static final int    _topology_name = 595636554;
    public static final String _topology_name_ = "topology-name";
    public static final int    _Stop_Simulation = 646475770;
    public static final String _Stop_Simulation_ = "Stop-Simulation";
}
