/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/cisco-virl-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ciscovirl.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module cisco-virl-stats.yang */
public class ciscovirlStats extends ConfNamespace {
    public static final int hash = 2087996136;
    public int hash() {
        return ciscovirlStats.hash;
    }

    public static final String id = "http://com/example/ciscovirl-stats";
    public String id() {
        return ciscovirlStats.id;
    }

    public static final String uri = "http://com/example/ciscovirl-stats";
    public String uri() {
        return ciscovirlStats.uri;
    }

    public static final String prefix = "cisco-virlstats";
    public String prefix() {
        return ciscovirlStats.prefix;
    }

    public ciscovirlStats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _reachable = 2025890210;
    public static final String _reachable_ = "reachable";
    public static final int    _topology = 333175635;
    public static final String _topology_ = "topology";
    public static final int    _excludeFromLaunch = 2125079005;
    public static final String _excludeFromLaunch_ = "excludeFromLaunch";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _expires = 217663303;
    public static final String _expires_ = "expires";
    public static final int    _simulation = 269615489;
    public static final String _simulation_ = "simulation";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _launched = 833896153;
    public static final String _launched_ = "launched";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _simulations = 1732650147;
    public static final String _simulations_ = "simulations";
}
